name: Test Schedule Trigger

on:
  schedule:
    - cron: "*/5 * * * *"  # สั่งให้รันทุก 5 นาที (เพื่อทดสอบระบบ)
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Date
        run: echo "Cron working at $(date)"
